// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA09Vn5vaoEsGmrzpcQ1ZGSCIo-YDw_Iso',
    appId: '1:317717748016:web:ade1830b5c68aa929050f5',
    messagingSenderId: '317717748016',
    projectId: 'resturant-booking-6a5e5',
    authDomain: 'resturant-booking-6a5e5.firebaseapp.com',
    storageBucket: 'resturant-booking-6a5e5.appspot.com',
    measurementId: 'G-J8K19428K3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkZmgss1Z7wLRD4Vu1Gzu1rjSt69KDbsA',
    appId: '1:317717748016:android:2865859838ce8cbe9050f5',
    messagingSenderId: '317717748016',
    projectId: 'resturant-booking-6a5e5',
    storageBucket: 'resturant-booking-6a5e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_nTvgjl4tU6PUOXJ3gWFgRLz3uFg5ii8',
    appId: '1:317717748016:ios:48e190668349243a9050f5',
    messagingSenderId: '317717748016',
    projectId: 'resturant-booking-6a5e5',
    storageBucket: 'resturant-booking-6a5e5.appspot.com',
    iosBundleId: 'com.example.jobizz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_nTvgjl4tU6PUOXJ3gWFgRLz3uFg5ii8',
    appId: '1:317717748016:ios:ffaf262752495c689050f5',
    messagingSenderId: '317717748016',
    projectId: 'resturant-booking-6a5e5',
    storageBucket: 'resturant-booking-6a5e5.appspot.com',
    iosBundleId: 'com.example.jobizz.RunnerTests',
  );
}
